Initial version of liblognorm API debugging methods implementation
teragrep/rsm_01 pull request #8
Opened 2024-12-13 06:52 UTC by Tiihott

Includes:
- Implementation for enabling debugging and error log messaging for liblognorm API (#7 ).
- Implementation of java callbacks for the log messages produced by liblognorm, allowing the logging to happen properly in java instead of C.

Also includes commits from PR #3, #5 and #6. Rebase may be needed in this PR after they have been merged to main.

2025-01-09 09:03 UTC, 51-code requested changes
Kept the review strictly to the latest commits (so just the `JavaLogNorm` classes) as requested. Didn't look too hard into the JNA interface as to my knowledge it is pretty standardized how it has to be done.

2025-01-09 09:03 UTC, 51-code commented on src/main/c/JavaLognorm.c
> +        // add exception handling here. ln_ returns null if error occurred.
I think this counts as a TODO comment. Create an issue about this. Issue #10 is pretty close with error handling but only mentions Java classes, so a new issue might be appropriate.

2025-01-09 09:03 UTC, 51-code commented on src/main/java/com/teragrep/rsm_01/JavaLognorm.java
> +public class JavaLognorm {
Class should be final.

2025-01-09 09:03 UTC, 51-code commented on src/main/java/com/teragrep/rsm_01/JavaLognorm.java
> +    JavaLognorm() {
Why is the constructor not public?

2025-01-09 09:03 UTC, 51-code commented on src/main/java/com/teragrep/rsm_01/LibJavaLognorm.java
> +    public static final LibJavaLognorm INSTANCE = Native.load("JavaLognorm", LibJavaLognorm.class);
I was rather confused by the naming of this variable when inspecting the JavaLognorm. Could this be renamed from INSTANCE to something that informs it points to this JNA interface?

2025-01-09 09:03 UTC, 51-code commented on src/main/java/com/teragrep/rsm_01/JavaLognorm.java
> +    public void liblognormExitCtx(Pointer ctx) {
This function does not have tests, just wanted to point this out. Looks as though the test would largely test the 3rd party library, so perhaps not needed.

2025-01-09 09:03 UTC, 51-code commented on src/test/java/com/teragrep/rsm_01/JavaLognormTest.java
> +        // Assert debug log messages here. Logs can include memory information so they are not identical in each run.
New issue to figure this out?

2025-01-09 09:03 UTC, 51-code commented on src/test/java/com/teragrep/rsm_01/JavaLognormTest.java
> +        // Assert error log messages here.
New issue to figure this out?

2025-01-09 09:03 UTC, 51-code commented on src/main/java/com/teragrep/rsm_01/JavaLognorm.java
> +            throw new IllegalArgumentException("LogNorm() not initialized.");
Maybe add an instruction, like "Use liblognormInitCtx()."?

2025-01-09 13:10 UTC, Tiihott commented on src/test/java/com/teragrep/rsm_01/JavaLognormTest.java
> +        // Assert error log messages here.
Created issue #11.

2025-01-09 13:10 UTC, Tiihott commented on src/test/java/com/teragrep/rsm_01/JavaLognormTest.java
> +        // Assert debug log messages here. Logs can include memory information so they are not identical in each run.
Created issue #11.

2025-01-09 13:11 UTC, Tiihott commented on src/main/c/JavaLognorm.c
> +        // add exception handling here. ln_ returns null if error occurred.
True. The ln_ctx context for liblognrom should also be encapsulated inside the java classes instead of using it as return value outside the rsm_01 library. The context can be considered as the identity of the object that interacts with the liblognorm library through JNA.
It also simplifies the rsm_01 usage as a library for issue #9.

Added TODO tag in commit: eb8e7889234afd04092cfc515b42431f20c0f19c

2025-01-09 13:23 UTC, Tiihott commented on src/main/java/com/teragrep/rsm_01/JavaLognorm.java
> +public class JavaLognorm {
Solved in commit: 2f3056f30e738a4b49412795ccf038a6c22740b2

2025-01-09 13:23 UTC, Tiihott commented on src/main/java/com/teragrep/rsm_01/JavaLognorm.java
> +    JavaLognorm() {
It was left as a placeholder while working on issue #9 implementing the needed java class structures to use the rsm_01 as a library.
Made constructor public in commit: 292176f843a26a640bbdece50440f4fb0fa5e3a1

2025-01-09 13:23 UTC, Tiihott commented on src/main/java/com/teragrep/rsm_01/LibJavaLognorm.java
> +    public static final LibJavaLognorm INSTANCE = Native.load("JavaLognorm", LibJavaLognorm.class);
INSTANCE naming is mentioned as a common practice in JNA documentations:
https://java-native-access.github.io/jna/5.12.1/javadoc/com/sun/jna/Library.html

For now renamed the field to jnaInstance on commit: ab9754b5c1ea80f602c4060cca0fe7b365d86147

2025-01-09 13:24 UTC, Tiihott commented on src/main/java/com/teragrep/rsm_01/JavaLognorm.java
> +    public void liblognormExitCtx(Pointer ctx) {
The method was missing return value implementation that can be used for java exception handling. Refactored the methods and added test asserting the return value.
Solved in commit: 6e444e69217f673c93c6b367e768da72d3045c6d

2025-01-09 13:34 UTC, Tiihott commented on src/main/java/com/teragrep/rsm_01/JavaLognorm.java
> +            throw new IllegalArgumentException("LogNorm() not initialized.");
Solved in commit: b23a5d19d56cce931bfbf29747784f7cfb031c33

2025-01-13 05:51 UTC, 51-code commented on src/main/c/JavaLognorm.c
> +        // add exception handling here. ln_ returns null if error occurred.
I think you can take the whole comment out now that there is an issue about it, TODO comments are usually not allowed. The idea about encapsulating ln_ctx sounds good.

2025-01-13 06:01 UTC, 51-code commented on src/main/java/com/teragrep/rsm_01/JavaLognorm.java
> +    public void liblognormExitCtx(Pointer ctx) {
Very nice!

2025-01-13 06:06 UTC, 51-code commented on src/test/java/com/teragrep/rsm_01/JavaLognormTest.java
> +        // Assert debug log messages here. Logs can include memory information so they are not identical in each run.
These comments could as well be taken out now that there is an issue.

2025-01-13 06:07 UTC, 51-code commented on src/test/java/com/teragrep/rsm_01/JavaLognormTest.java
> +        // Assert error log messages here.
Comment could be taken out. ^

2025-01-13 06:43 UTC, Tiihott commented on src/main/c/JavaLognorm.c
> +        // add exception handling here. ln_ returns null if error occurred.
Removed comment on commit: cff6ac2daf6a3b7adb1824c94d70e99f077c5646

2025-01-13 06:44 UTC, Tiihott commented on src/test/java/com/teragrep/rsm_01/JavaLognormTest.java
> +        // Assert debug log messages here. Logs can include memory information so they are not identical in each run.
Removec comment on commit: cff6ac2daf6a3b7adb1824c94d70e99f077c5646

2025-01-13 06:44 UTC, Tiihott commented on src/test/java/com/teragrep/rsm_01/JavaLognormTest.java
> +        // Assert error log messages here.
Removec comment on commit: cff6ac2daf6a3b7adb1824c94d70e99f077c5646

2025-01-13 07:03 UTC, 51-code approved these changes
LGTM!

2025-01-27 16:12 UTC, kortemik commented
please close if #13 superseded this

2025-01-28 12:06 UTC, Tiihott commented
Superseded by the already merged #13

2025-01-28 12:06 UTC, closed without merging